-- egene66_nextrade.eso_cm definition

CREATE TABLE `eso_cm` (
  `CM_ID` varchar(30) NOT NULL,
  `CM_CAT_CD` varchar(100) DEFAULT NULL COMMENT '범주',
  `CM_CLA_CD` mediumtext DEFAULT NULL,
  `CM_REG_DTTM` varchar(14) DEFAULT NULL,
  `CM_STA_CD` mediumtext DEFAULT NULL,
  `CM_REMARK` text DEFAULT NULL,
  `CM_MGR_EMP_ID` mediumtext DEFAULT NULL,
  `CM_AST_ID` mediumtext DEFAULT NULL,
  `CM_USE_CD` mediumtext DEFAULT NULL COMMENT '용도',
  `CM_SYS_NAME` mediumtext DEFAULT NULL,
  `CM_MAKE_NAME` mediumtext DEFAULT NULL COMMENT '제조사',
  `CM_IP` mediumtext DEFAULT NULL,
  `CM_DUAL_YN` varchar(1) DEFAULT NULL,
  `CM_OS` mediumtext DEFAULT NULL COMMENT 'OS',
  `CM_OS_VERSION` mediumtext DEFAULT NULL COMMENT '운영체제 버전',
  `CM_CPU_SPEED` mediumtext DEFAULT NULL COMMENT 'CPU 속도',
  `CM_MEMORY` mediumtext DEFAULT NULL COMMENT '메모리크기(단위:MB)',
  `CM_NAME` mediumtext DEFAULT NULL COMMENT 'CI 명',
  `CM_DR_YN` varchar(1) DEFAULT NULL COMMENT 'DR서버구축여부',
  `CM_OS_BACK_YN` varchar(1) DEFAULT NULL,
  `CM_DISK` text DEFAULT NULL,
  `CM_PATCH` text DEFAULT NULL,
  `CM_DISK_NUM` mediumtext DEFAULT NULL COMMENT '디스크 수',
  `CM_SLOT_NUM` mediumtext DEFAULT NULL,
  `CM_CAPA` mediumtext DEFAULT NULL COMMENT '용량',
  `CM_USE_NUM` mediumtext DEFAULT NULL,
  `CM_LICENSE_TYPE` mediumtext DEFAULT NULL COMMENT '라이센스 유형',
  `CM_LICENSE_NUM` mediumtext DEFAULT NULL COMMENT '라이센스 수',
  `CM_PORT` mediumtext DEFAULT NULL COMMENT '포트',
  `CM_MODEL_NAME` mediumtext DEFAULT NULL COMMENT '모델명',
  `CM_HOSTNAME` mediumtext DEFAULT NULL,
  `CM_TAKIN_DTTM` mediumtext DEFAULT NULL,
  `CM_TAKIN_SUM` decimal(10,0) DEFAULT NULL,
  `CM_DUR_ST_DT` varchar(14) DEFAULT NULL,
  `CM_DUR_ST_ET` varchar(14) DEFAULT NULL,
  `CM_AST_NO` mediumtext DEFAULT NULL,
  `CM_SHAPE` mediumtext DEFAULT NULL,
  `CM_WRT_DT` varchar(8) DEFAULT NULL,
  `CM_MTN_YN` mediumtext DEFAULT NULL,
  `CM_TOTAL_AMNT` int(11) DEFAULT NULL,
  `CM_MTH_AMNT` int(11) DEFAULT NULL,
  `CM_LOC_DET` mediumtext DEFAULT NULL,
  `CM_VIRT_YN` varchar(1) DEFAULT NULL,
  `CM_CPU_CORE_CNT` int(11) DEFAULT NULL COMMENT '전체 CPU Core',
  `CM_OS_BACK_INVOLVE_YN` mediumtext DEFAULT NULL COMMENT '백업대상',
  `CM_BACK_DATA_YN` varchar(1) DEFAULT NULL,
  `CM_BACK_DATA_INVOLVE_YN` varchar(1) DEFAULT NULL,
  `CM_FLASH` mediumtext DEFAULT NULL,
  `CM_PWR_DUAL_YN` varchar(1) DEFAULT NULL,
  `CM_DISK_SPEED` mediumtext DEFAULT NULL,
  `CM_MIR_YN` varchar(1) DEFAULT NULL,
  `CM_SAN_SWC` mediumtext DEFAULT NULL,
  `CM_HOST_ACP` mediumtext DEFAULT NULL,
  `CM_UNIT` mediumtext DEFAULT NULL,
  `CM_REAL_NUM` mediumtext DEFAULT NULL,
  `CM_EX_NUM` int(11) DEFAULT NULL COMMENT '여유수량',
  `CM_USER_EMP_ID` mediumtext DEFAULT NULL,
  `CM_USER_DPT_ID` mediumtext DEFAULT NULL,
  `CM_MTN_EMP_ID` mediumtext DEFAULT NULL,
  `CM_USED` varchar(1) DEFAULT NULL COMMENT '사용여부',
  `CM_ACP_CONTENT` mediumtext DEFAULT NULL,
  `CM_ACP_DTTM` varchar(14) DEFAULT NULL,
  `CM_ACP_EMP_ID` mediumtext DEFAULT NULL,
  `CM_ACTFINISH_DTTM` varchar(14) DEFAULT NULL,
  `CM_ACTSTART_DTTM` varchar(14) DEFAULT NULL,
  `CM_ACT_CONTENT` mediumtext DEFAULT NULL,
  `CM_ACT_DTTM` varchar(14) DEFAULT NULL,
  `CM_ACT_EMP_ID` mediumtext DEFAULT NULL,
  `CM_AGREE_DTTM` varchar(14) DEFAULT NULL,
  `CM_ASR_EMP_ID` mediumtext DEFAULT NULL,
  `CM_ASR_WOG_ID` mediumtext DEFAULT NULL,
  `CM_ASS_DPT_ID` mediumtext DEFAULT NULL,
  `CM_ASS_EMP_ID` mediumtext DEFAULT NULL,
  `CM_ASS_ORG_ID` mediumtext DEFAULT NULL,
  `CM_ASS_WOG_ID` mediumtext DEFAULT NULL COMMENT '처리자작업그룹',
  `CM_CIT_ID` mediumtext DEFAULT NULL,
  `CM_CLO_CD` mediumtext DEFAULT NULL,
  `CM_CLO_DTTM` varchar(14) DEFAULT NULL,
  `CM_DEAD_DTTM` varchar(14) DEFAULT NULL,
  `CM_MED_CD` mediumtext DEFAULT NULL,
  `CM_OWN_DPT_ID` varchar(100) DEFAULT NULL COMMENT '소유자부서',
  `CM_OWN_EMP_ID` mediumtext DEFAULT NULL,
  `CM_OWN_ORG_ID` mediumtext DEFAULT NULL,
  `CM_PLANFINISH_DTTM` varchar(14) DEFAULT NULL,
  `CM_PLANSTART_DTTM` varchar(14) DEFAULT NULL COMMENT '계획시작일시',
  `CM_PLAN_CONTENT` mediumtext DEFAULT NULL,
  `CM_REG_DPT_ID` mediumtext DEFAULT NULL COMMENT '등록자부서',
  `CM_REG_EMP_ID` mediumtext DEFAULT NULL,
  `CM_REG_ORG_ID` mediumtext DEFAULT NULL,
  `CM_REQ_CONTENT` mediumtext DEFAULT NULL COMMENT '요청내용',
  `CM_REQ_DPT_ID` mediumtext DEFAULT NULL COMMENT '요청자부서',
  `CM_REQ_DTTM` varchar(14) DEFAULT NULL COMMENT '요청일시',
  `CM_REQ_EMP_ID` mediumtext DEFAULT NULL COMMENT '요청자',
  `CM_REQ_ORG_ID` mediumtext DEFAULT NULL COMMENT '요청자기관',
  `CM_REQ_TITLE` mediumtext DEFAULT NULL COMMENT '요청제목',
  `CM_SVC_ID` mediumtext DEFAULT NULL COMMENT '서비스',
  `CM_SYS_ID` mediumtext DEFAULT NULL COMMENT '업무시스템',
  `CM_TAS_ID` mediumtext DEFAULT NULL COMMENT 'Task',
  `CM_PID` varchar(100) DEFAULT NULL COMMENT '상위아이디',
  `CM_MOD_DTTM` varchar(14) DEFAULT NULL COMMENT '수정일시',
  `CM_MOD_EMP_ID` mediumtext DEFAULT NULL COMMENT '수정자',
  `CM_PLACE` mediumtext DEFAULT NULL COMMENT '설치장소',
  `CM_SRC_ID` mediumtext DEFAULT NULL,
  `CM_RACK_LOC` mediumtext DEFAULT NULL COMMENT 'Rack 위치',
  `CM_CTR_NO` mediumtext DEFAULT NULL COMMENT '유지보수계약번호',
  `CM_MGR_EMP_PHONE` mediumtext DEFAULT NULL COMMENT '담당자연락처',
  `CM_SALES_EMP_NAME` mediumtext DEFAULT NULL COMMENT '영업담당자',
  `CM_SALES_EMP_PHONE` mediumtext DEFAULT NULL COMMENT '영업담당자연락처',
  `CM_FMTN_YN` varchar(1) DEFAULT NULL COMMENT '유지보수무상여부',
  `CM_CTR_ORG` mediumtext DEFAULT NULL COMMENT '계약업체명',
  `CM_CTR_NO_NAME` mediumtext DEFAULT NULL COMMENT '유지보수계약명',
  `CM_CPU_CNT` int(11) DEFAULT NULL COMMENT 'CPU 수',
  `CM_DB_DUAL_YN` varchar(1) DEFAULT NULL COMMENT 'DB 이중화 여부',
  `CM_DB_INSTANCE_NAME` mediumtext DEFAULT NULL COMMENT 'DB Instance 명',
  `CM_DEV_FRAMEWORK` mediumtext DEFAULT NULL COMMENT '개발 프레임워크',
  `CM_DEV_LANGUAGE` mediumtext DEFAULT NULL COMMENT '개발언어',
  `CM_DISK_MOUNT_SIZE` int(11) DEFAULT NULL COMMENT '디스크별 사이즈(GB)',
  `CM_DISK_SIZE` mediumtext DEFAULT NULL COMMENT '제공 총 용량(GB)',
  `CM_DISK_SPARE` varchar(1) DEFAULT NULL,
  `CM_EOL_DT` mediumtext DEFAULT NULL COMMENT '기술지원 종료일자',
  `CM_EXTERNAL_STORAGE_YN` varchar(1) DEFAULT NULL,
  `CM_FIREWALL_YN` varchar(1) DEFAULT NULL,
  `CM_LINUX_SUPPORT_YN` varchar(1) DEFAULT NULL,
  `CM_MGR_DPT_ID` mediumtext DEFAULT NULL,
  `CM_MTN_EMP_PHONE` mediumtext DEFAULT NULL COMMENT '유지보수 담당자 연락처',
  `CM_NET_CD` mediumtext DEFAULT NULL,
  `CM_PACKAGE_NAME` mediumtext DEFAULT NULL,
  `CM_PACKAGE_SUPPLIER` mediumtext DEFAULT NULL,
  `CM_PARTITION_CNT` mediumtext DEFAULT NULL COMMENT '파티션 개수',
  `CM_PARTITION_SIZE` mediumtext DEFAULT NULL COMMENT '파티션별 사이즈(GB)',
  `CM_REL_WOG_ID` mediumtext DEFAULT NULL,
  `CM_SERIAL_NO` mediumtext DEFAULT NULL,
  `CM_SUB_IP` mediumtext DEFAULT NULL,
  `CM_SUPPLIER` mediumtext DEFAULT NULL,
  `CM_SYS_CLOUD_YN` varchar(1) DEFAULT NULL,
  `CM_SYS_FUNCTION` mediumtext DEFAULT NULL,
  `CM_SYS_GRADE` mediumtext DEFAULT NULL COMMENT '중요도',
  `CM_SYS_URL` mediumtext DEFAULT NULL COMMENT '접속URL',
  `CM_USE_TEXT` mediumtext DEFAULT NULL COMMENT '세부용도',
  `CM_VERSION` mediumtext DEFAULT NULL COMMENT '버전',
  `CM_SVCGRD_CD` mediumtext DEFAULT NULL COMMENT '서비스 등급',
  `CM_TAKIN_METHOD` mediumtext DEFAULT NULL COMMENT '도입방법',
  `CM_MTN_ID` mediumtext DEFAULT NULL COMMENT 'MTN_ID',
  `CM_ORDER` int(11) DEFAULT NULL COMMENT '순서',
  `CM_SYS_CLS_CD` mediumtext DEFAULT NULL COMMENT '시스템 범주',
  `CM_APP_ID` mediumtext DEFAULT NULL COMMENT '어플리케이션 ID',
  `CM_OA_CAT_CD` mediumtext DEFAULT NULL COMMENT '구분',
  `CM_SOFTW` mediumtext DEFAULT NULL COMMENT '소프트웨어',
  `cm_oa_name` varchar(255) DEFAULT NULL,
  `CM_SW_LIC_CD` mediumtext DEFAULT NULL COMMENT '라이선스 방식',
  `CM_OSS` mediumtext DEFAULT NULL COMMENT 'OSS',
  `CM_EOS` mediumtext DEFAULT NULL COMMENT 'EOS',
  `CM_EMP_DPT` mediumtext DEFAULT NULL COMMENT '담당부서',
  `CM_MNG` mediumtext DEFAULT NULL COMMENT '관리자',
  `CM_MGRT_EMP_ID` mediumtext DEFAULT NULL COMMENT '관리책임자',
  `CM_EQU_DOM` mediumtext DEFAULT NULL COMMENT '장비도메인',
  `CM_UNIT_SYS` mediumtext DEFAULT NULL COMMENT '단위시스템',
  `CM_EQU_NAME` mediumtext DEFAULT NULL COMMENT '장비명',
  `CM_LOCA` mediumtext DEFAULT NULL COMMENT '위치',
  `CM_CIRCU` mediumtext DEFAULT NULL COMMENT '환경',
  `CM_SERVER_TYPE` mediumtext DEFAULT NULL COMMENT '서버형태',
  `CM_CLIUS_MED` mediumtext DEFAULT NULL COMMENT '클러스터 방식',
  `CM_VIR_CLUS_NAME` mediumtext DEFAULT NULL COMMENT '가상화 클러스터 명',
  `CM_HOST_GROUP` mediumtext DEFAULT NULL COMMENT '호스트그룹',
  `CM_HOST_NAME` varchar(255) DEFAULT NULL,
  `CM_HYPER_REPOS` mediumtext DEFAULT NULL COMMENT 'Hypervisor Repository 사용량 (GB)',
  `CM_IMP_LEVEL` mediumtext DEFAULT NULL COMMENT '중요도 등급',
  `CM_PORT1` mediumtext DEFAULT NULL COMMENT 'port1',
  `CM_PORT2` mediumtext DEFAULT NULL COMMENT 'port2',
  `CM_CPU_SOCKET` mediumtext DEFAULT NULL COMMENT 'Socket (CPU)',
  `CM_VOLINF` mediumtext DEFAULT NULL COMMENT '볼륨정보',
  `CM_FIR_VOLINF` mediumtext DEFAULT NULL COMMENT '초기 볼륨정보',
  `CM_OS_HBA_WWN` mediumtext DEFAULT NULL COMMENT 'OS HBA WWN , 가상화 WWNN / WWWNP',
  `CM_SWAP` int(11) DEFAULT NULL COMMENT 'swap(GB)',
  `CM_TIMESERVER_TYPE` mediumtext DEFAULT NULL COMMENT 'TimeServer Type',
  `CM_HYPER_THREADING` mediumtext DEFAULT NULL COMMENT 'Hyper Threading 사용유',
  `CM_RACK_NO` mediumtext DEFAULT NULL COMMENT 'Rack No',
  `CM_RACK_NUM` mediumtext DEFAULT NULL COMMENT '승인번호 (자산매칭)',
  `CM_TAKIN_CON_NAME` mediumtext DEFAULT NULL COMMENT '도입  계약명',
  `CM_HW_EOS` mediumtext DEFAULT NULL COMMENT 'Hardware EoS',
  `CM_SW_EOS` mediumtext DEFAULT NULL COMMENT 'Softward  EoS',
  `CM_BACK` mediumtext DEFAULT NULL COMMENT '백업정책',
  `CM_BACK_TEXT` mediumtext DEFAULT NULL COMMENT '백업정책내용',
  `CM_S1P1_NIC1` mediumtext DEFAULT NULL COMMENT 'NIC1(S1P1)',
  `CM_S5P1_NIC2` mediumtext DEFAULT NULL COMMENT 'NIC2(S5P1)',
  `CM_S3P1_NIC1` mediumtext DEFAULT NULL COMMENT 'NIC1(S3P1)',
  `CM_S4P1_NIC2` mediumtext DEFAULT NULL COMMENT 'NIC2(S4P1)',
  `CM_S3P2_NIC1` mediumtext DEFAULT NULL COMMENT 'NIC1(S3P2)',
  `CM_S4P2_NIC2` mediumtext DEFAULT NULL COMMENT 'NIC2(S4P2)',
  `CM_S3P3_NIC1` mediumtext DEFAULT NULL COMMENT 'NIC1(S3P3)',
  `CM_S4P3_NIC2` mediumtext DEFAULT NULL COMMENT 'NIC2(S4P3)',
  `CM_S3P4_NIC1` mediumtext DEFAULT NULL COMMENT 'NIC1(S3P4)',
  `CM_S4P4_NIC2` mediumtext DEFAULT NULL COMMENT 'NIC2(S4P4)',
  `CM_GRD_C` varchar(14) DEFAULT NULL COMMENT 'C(자산등급)',
  `CM_GRD_I` varchar(14) DEFAULT NULL COMMENT 'I(자산등급)',
  `CM_GRD_A` varchar(14) DEFAULT NULL COMMENT 'A(자산등급)',
  `CM_DELIVERY_DATE` varchar(14) DEFAULT NULL COMMENT '납품일자',
  `CM_EMP_TITLE_CD` mediumtext DEFAULT NULL COMMENT '직책',
  `CM_HDD` mediumtext DEFAULT NULL COMMENT '하드디스크',
  `CM_HDD2` mediumtext DEFAULT NULL COMMENT '하드디스크2',
  `CM_USED_OFFICE` varchar(14) DEFAULT NULL COMMENT 'Office 사용',
  `CM_USED_KOR` varchar(14) DEFAULT NULL COMMENT '한글사용',
  `CM_OFFICE_MAK` mediumtext DEFAULT NULL COMMENT '오피스 MAK',
  `cm_se_num` varchar(255) DEFAULT NULL,
  `CM_USED_CD` varchar(14) DEFAULT NULL COMMENT '이전용도',
  `CM_TO_BUY` varchar(14) DEFAULT NULL COMMENT '구입처',
  `CM_DISK_SIZE2` mediumtext DEFAULT NULL COMMENT 'cm_disk_size2',
  `CM_LICENSE_TYPE4` mediumtext DEFAULT NULL COMMENT 'cm_license_type4',
  `CM_MTN_DPT_ID` mediumtext DEFAULT NULL COMMENT 'cm_mtn_dpt_id',
  `cm_mtn_content` mediumtext DEFAULT NULL,
  `CM_USER_DPT` mediumtext DEFAULT NULL COMMENT '부서명',
  `CM_USER_EMP` mediumtext DEFAULT NULL COMMENT '사용자',
  `CM_MEMORY2` mediumtext DEFAULT NULL COMMENT 'cm_memory2',
  `CM_LICENSE_TYPE2` mediumtext DEFAULT NULL COMMENT 'cm_license_type2',
  `CM_LICENSE_TYPE3` mediumtext DEFAULT NULL COMMENT 'cm_license_type3',
  `CM_PTP_PORT1` mediumtext DEFAULT NULL COMMENT 'cm_PTP_Port1',
  `CM_PTP_PORT2` mediumtext DEFAULT NULL COMMENT 'cm_PTP_Port2',
  `CM_IDAC_IP` mediumtext DEFAULT NULL COMMENT 'cm_idac_IP',
  `CM_REAR_TYPE` mediumtext DEFAULT NULL COMMENT '후면타입',
  `CM_CPU_CORE_CNT1` mediumtext DEFAULT NULL COMMENT 'cm_cpu_core_cnt1',
  `CM_CPU_CORE_CNT2` varchar(6) DEFAULT NULL COMMENT 'cm_cpu_core_cnt2',
  `CM_CPU_CORE_CNT3` varchar(6) DEFAULT NULL COMMENT 'cm_cpu_core_cnt3',
  `CM_EX_NUM2` varchar(6) DEFAULT NULL COMMENT 'cm_ex_num2',
  `CM_NET_CD2` mediumtext DEFAULT NULL COMMENT '망구분',
  `CM_MAKE_NAME2` mediumtext DEFAULT NULL COMMENT '제조사',
  `CM_USE_CD2` mediumtext DEFAULT NULL COMMENT '용도',
  `CM_NET_CD3` mediumtext DEFAULT NULL COMMENT '대상',
  `CM_GUBUN` mediumtext DEFAULT NULL COMMENT '구분',
  `CM_COUNT1` mediumtext DEFAULT NULL COMMENT '대수',
  `CM_CORE1` mediumtext DEFAULT NULL COMMENT 'core',
  `CM_COUNT2` mediumtext DEFAULT NULL COMMENT '대수',
  `CM_CORE2` mediumtext DEFAULT NULL COMMENT 'core',
  `CM_COUNT3` mediumtext DEFAULT NULL COMMENT '대수',
  `CM_CORE3` mediumtext DEFAULT NULL COMMENT 'core',
  `CM_TOPOLOGY` mediumtext DEFAULT NULL COMMENT 'Topology',
  `CM_IDRACIP` mediumtext DEFAULT NULL COMMENT 'Port 1',
  `CM_CPU_MAKE_NAME` mediumtext DEFAULT NULL COMMENT '제조사',
  `CM_CPU_TYPE` mediumtext DEFAULT NULL COMMENT 'Type',
  `CM_CPU_CLOCK` mediumtext DEFAULT NULL COMMENT 'Clock (GHz)',
  `CM_CPU_CORE_VCPU` mediumtext DEFAULT NULL COMMENT 'Core_vCPU',
  `CM_MEMORY_SIZE` mediumtext DEFAULT NULL COMMENT 'Size (MB)',
  `CM_MEMORY_CONSTITUTE` mediumtext DEFAULT NULL COMMENT '구성',
  `CM_MEMORY_TYPE` mediumtext DEFAULT NULL COMMENT 'Type',
  `CM_MEMORY_VMSIZE` mediumtext DEFAULT NULL COMMENT 'Vm Size(MB)',
  `CM_HDD_SIZE` mediumtext DEFAULT NULL COMMENT 'Size (GB)',
  `CM_HDD_CNT` int(11) DEFAULT NULL COMMENT '수량',
  `CM_HDD_TYPE` mediumtext DEFAULT NULL COMMENT 'Type',
  `CM_HDD_RAID` mediumtext DEFAULT NULL COMMENT 'Raid',
  `CM_HDD_TOTAL_SIZE` mediumtext DEFAULT NULL COMMENT '총 할당량 (GB)',
  `CM_STORAGE_LUN` mediumtext DEFAULT NULL COMMENT 'LUN (GB)',
  `CM_STORAGE_LUN_ENT` int(11) DEFAULT NULL COMMENT 'LUN 수',
  `CM_STORAGE_TYPE` mediumtext DEFAULT NULL COMMENT '타입',
  `CM_STORAGE_TARGET` mediumtext DEFAULT NULL COMMENT '대상',
  `CM_OBJ_MAKE_NAME` mediumtext DEFAULT NULL COMMENT '제조사',
  `CM_GET_DAY` mediumtext DEFAULT NULL COMMENT '자산 취득일자',
  `CM_MTN_WORKER` mediumtext DEFAULT NULL COMMENT '유지보수 담당자',
  `CM_CASE1_GUBUN` varchar(14) DEFAULT NULL COMMENT '구분',
  `CM_CASE1_COUNT1` int(11) DEFAULT NULL COMMENT '대수',
  `CM_CASE1_CORE1` int(11) DEFAULT NULL COMMENT 'Core',
  `CM_CASE1_COUNT2` int(11) DEFAULT NULL COMMENT '대수',
  `CM_CASE1_CORE2` int(11) DEFAULT NULL COMMENT 'Core',
  `CM_CASE2_GUBUN` mediumtext DEFAULT NULL COMMENT '구분',
  `CM_CASE2_COUNT1` int(11) DEFAULT NULL COMMENT '대수',
  `CM_CASE2_CORE1` int(11) DEFAULT NULL COMMENT 'Core',
  `CM_CASE2_COUNT2` int(11) DEFAULT NULL COMMENT '대수',
  `CM_CASE2_CORE2` int(11) DEFAULT NULL COMMENT 'Core',
  `CM_CURRENT_COUNT` int(11) DEFAULT NULL COMMENT '대수',
  `CM_CURRENT_CORE` int(11) DEFAULT NULL COMMENT 'Core',
  `CM_LUN_SIZE_CNT` int(11) DEFAULT NULL,
  `CM_CLUS_LOC` mediumtext DEFAULT NULL COMMENT '할당 클러스터 위치',
  `CM_DATASTORE` mediumtext DEFAULT NULL COMMENT '할당 데이터스토어',
  `CM_SAN_DESC` mediumtext DEFAULT NULL COMMENT 'SAN 정보 요약',
  PRIMARY KEY (`CM_ID`),
  UNIQUE KEY `uq_cm_host_name` (`CM_HOST_NAME`),
  UNIQUE KEY `uq_cm_oa_name` (`cm_oa_name`),
  UNIQUE KEY `uq_cm_se_num` (`cm_se_num`),
  KEY `IX_ESO_CM_01` (`CM_PID`,`CM_USED`,`CM_CAT_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;