SELECT
		A.B_DT AS name -- DT
	  , IFNULL(SUM(CASE WHEN B.ENT_ID = 'SR' THEN CNT END), 0) AS '서비스요청'
	  , IFNULL(SUM(CASE WHEN B.ENT_ID = 'CH' THEN CNT END), 0) AS '어플리케이션변경'
  FROM  (
		SELECT SUBSTR(HOD_ID, 1, 6) AS B_DT
		  FROM ECF_HOLIDAY  
		-- WHERE SUBSTR(HOD_ID, 1, 6) BETWEEN DATE_FORMAT(DATE_ADD(NOW(), INTERVAL -5 MONTH), '%Y%m') AND DATE_FORMAT(NOW(), '%Y%m') 
		GROUP BY SUBSTR(HOD_ID, 1, 6)
		) A JOIN 
		(
		SELECT 
			    SUBSTR(SRM_REQ_DTTM, 1, 6) AS R_DT
			  , 'SR' AS ENT_ID
			  , 1 AS CNT
			  , SRM_REG_EMP_ID AS REG_EMP_ID
		  FROM ESO_SRM
      WHERE SRM_TAS_ID NOT IN ('TAS01632','TAS01776')	/* 임시저장, 취소종료 제외 */
		-- WHERE SUBSTR(SRM_REQ_DTTM, 1, 6) BETWEEN DATE_FORMAT(DATE_ADD(NOW(), INTERVAL -5 MONTH), '%Y%m') AND DATE_FORMAT(NOW(), '%Y%m')
		 
		UNION ALL  

		SELECT 
			    SUBSTR(CHM_REQ_DTTM, 1, 6) AS R_DT
			  , 'CH' AS ENT_ID
			  , 1 AS CNT
			  , CHM_REG_EMP_ID AS REG_EMP_ID
		  FROM ESO_CHM
		-- WHERE SUBSTR(CHM_REQ_DTTM, 1, 6) BETWEEN DATE_FORMAT(DATE_ADD(NOW(), INTERVAL -5 MONTH), '%Y%m') AND DATE_FORMAT(NOW(), '%Y%m')
		 WHERE chm_typ_cd = 'CHMTYP020'  /*AP변경*/
		) B ON A.B_DT = B.R_DT
  WHERE 1=1
  and SUBSTR(A.B_DT, 1, 6) BETWEEN CASE WHEN  '{dateval}'  = '{dateval}' THEN DATE_FORMAT(DATE_ADD(NOW(), INTERVAL -5 MONTH), '%Y%m') ELSE DATE_FORMAT(DATE_ADD(STR_TO_DATE(CONCAT( '{dateval}' , '01'), '%Y%m%d'), INTERVAL -5 MONTH), '%Y%m') END AND CASE WHEN  '{dateval}'  = '{dateval}' THEN DATE_FORMAT(NOW(), '%Y%m') ELSE  '{dateval}'  END and REG_EMP_ID REGEXP (CASE WHEN  '.*'  = '{selectval}' THEN '.*' ELSE  '.*'  END)		
GROUP BY A.B_DT
ORDER BY A.B_DT