WITH RECURSIVE COD_TMP AS (
  SELECT COD_ID, COD_NAME, COD_PID, T.COD_ID AS ROOT_ID, 1 AS LEV, COD_NAME AS COD_PATH
    FROM ECF_CODE T 
    WHERE COD_CTY_ID = 'SRMCAT' 
      AND COD_USED = '1'
      AND COD_PID IS NULL

  UNION ALL 
            
  SELECT T.COD_ID, T.COD_NAME, T.COD_PID, P.ROOT_ID, P.LEV+1 AS LEV, CONCAT(P.COD_PATH, '>', T.COD_NAME) AS COD_PATH
    FROM ECF_CODE T, COD_TMP P
    WHERE T.COD_PID = P.COD_ID 
      AND COD_USED = '1'
) 
SELECT 
    COD_ID AS ID
  , COD_NAME
  , COD_PATH AS NAME
FROM COD_TMP
WHERE COD_PID IN (/*'SRMNXTCAT020', 'SRMNXTCAT030','SRMNXTCAT040', 'SRMNXTCAT050',*//* 계정, OA, 보안, 권한 */
                  'SRMNXT2CAT010','SRMNXT2CAT020','SRMNXT2CAT030','SRMNXT2CAT060') /* 개선 - 계정 및 권한 신청, OA 요청, 보안요청, 작업요청 */		
  AND COD_ID LIKE 'SR%'
ORDER BY COD_PATH